language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential make cmake libsndfile1-dev

install:
  - mkdir build
  - cd build
  - cmake .. -DUSE_SYSTEM_SNDFILE=1

script:
  - make -j4

