language: c

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential make cmake libsndfile1-dev 
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

install:
  - mkdir build
  - cd build
  - cmake .. -DUSE_SYSTEM_SNDFILE=1

script:
  - make -j4

