language: c

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get -qq update
  - sudo apt-get -qq install build-essential make cmake libsndfile1-dev liblzma-dev
  - sudo apt-get -qq build-dep cmake
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq gcc-4.9 g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.0.tar.gz
  - tar xf cmake-3.3.0.tar.gz
  - pushd cmake-3.3.0 && ./bootstrap --prefix=/usr --system-libs --mandir=/share/man --no-system-jsoncpp --docdir=/share/doc/cmake-3.3.0 > /dev/null && make -j5 && sudo make install
  - popd

install:
  - mkdir build
  - cd build
  - CC=gcc-4.9 CXX=g++-4.9 cmake .. -DUSE_SYSTEM_SNDFILE=1

script:
  - make -j4

